#!/usr/bin/env python3
"""Generate bgpd no-op northbound stubs from a missing-callbacks TSV.

Input format (one line per missing callback):
    <op>\\t<xpath>

Where <op> is one of: create, modify, destroy, get_next, get_keys,
lookup_entry.

Output:
    bgpd/bgp_nb_stubs_table.inc -- nodes-table fragment, suitable for
        #include inside the .nodes = { ... } initializer of
        frr_bgp_info in bgpd/bgp_nb.c.

The stub function symbols themselves live in bgpd/bgp_nb_stubs.c and
are declared in bgpd/bgp_nb_stubs.h; this generator only emits the
table entries.

Idempotent: rerun whenever the YANG tree changes and the diff appears
in the .inc file.
"""
import collections
import os
import sys

OP_TO_CB = {
    "create": "bgp_nb_stub_create",
    "modify": "bgp_nb_stub_modify",
    "destroy": "bgp_nb_stub_destroy",
    "get_next": "bgp_nb_stub_get_next",
    "get_keys": "bgp_nb_stub_get_keys",
    "lookup_entry": "bgp_nb_stub_lookup_entry",
}


def main(tsv_path: str, out_path: str) -> int:
    by_xpath: dict[str, set[str]] = collections.defaultdict(set)
    with open(tsv_path) as fh:
        for line in fh:
            line = line.rstrip("\n")
            if not line or not line.startswith(("create\t", "modify\t",
                                                "destroy\t", "get_next\t",
                                                "get_keys\t",
                                                "lookup_entry\t")):
                continue
            op, xpath = line.split("\t", 1)
            if op in OP_TO_CB:
                by_xpath[xpath].add(op)

    if not by_xpath:
        print(f"no stub entries parsed from {tsv_path}", file=sys.stderr)
        return 1

    lines = []
    lines.append("/* SPDX-License-Identifier: GPL-2.0-or-later */")
    lines.append("/*")
    lines.append(" * Auto-generated by tools/gen-bgp-nb-stubs.py.")
    lines.append(" * Do not edit by hand. Regenerate by running:")
    lines.append(" *   python3 tools/gen-bgp-nb-stubs.py "
                 "tools/missing_cbs.tsv "
                 "bgpd/bgp_nb_stubs_table.inc")
    lines.append(" *")
    lines.append(" * Each entry binds a YANG node to no-op callbacks so that")
    lines.append(" * nb_validate_callbacks() passes for the frr-bgp module")
    lines.append(" * tree. Real handlers for any of these xpaths should be")
    lines.append(" * added to bgp_nb.c (above the #include of this file)")
    lines.append(" * and the corresponding line removed from this file or")
    lines.append(" * from tools/missing_cbs.tsv before regeneration.")
    lines.append(" */")
    lines.append("")
    for xpath in sorted(by_xpath):
        ops = by_xpath[xpath]
        cb_lines = []
        for op in sorted(ops):
            cb_lines.append(f".{op} = {OP_TO_CB[op]},")
        cb_block = " ".join(cb_lines)
        lines.append(f'{{ .xpath = "{xpath}",')
        lines.append(f'  .cbs = {{ {cb_block} }} }},')

    out_dir = os.path.dirname(out_path)
    if out_dir:
        os.makedirs(out_dir, exist_ok=True)
    with open(out_path, "w") as fh:
        fh.write("\n".join(lines) + "\n")
    print(f"wrote {out_path}: {len(by_xpath)} xpath stub entries",
          file=sys.stderr)
    return 0


if __name__ == "__main__":
    if len(sys.argv) != 3:
        print(f"usage: {sys.argv[0]} <missing_cbs.tsv> <out.inc>",
              file=sys.stderr)
        sys.exit(2)
    sys.exit(main(sys.argv[1], sys.argv[2]))
